; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
;   Board: ESP32 Dev Module
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_RUNNING_CORE=1
    -DCONFIG_ARDUINO_EVENTS_RUN_CORE=1
    -I src
    -I src/rtos
    -I src/common
    -I src/control/config
    -I src/control/data
    -I src/control/tasks
    -I src/control/drivers
    -I src/sensors/config
    -I src/sensors/data
    -I src/sensors/tasks
    -I src/sensors/drivers
    -I src/actuation
    -I src/actuation/config
    -I src/actuation/data
    -I src/actuation/tasks
    -I src/actuation/drivers
    -I src/identification/config
    -I src/identification/data
    -I src/identification/tasks
    -I src/identification/drivers
    -I src/communication/config
    -I src/communication/data
    -I src/communication/tasks
    -I src/communication/drivers
    -I src/display/config
    -I src/display/data
    -I src/display/tasks
    -I src/display/drivers